//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WonderCook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        public Recipes()
        {
            this.Ingredients = new HashSet<Ingredients>();
            this.Macro_Ingredients = new HashSet<Macro_Ingredients>();
        }
    
        public int recipe_id { get; set; }
        public string recipe_name { get; set; }
        public string image { get; set; }
        public string how_to_make { get; set; }
    
        public virtual ICollection<Ingredients> Ingredients { get; set; }
        public virtual ICollection<Macro_Ingredients> Macro_Ingredients { get; set; }
    }
}
